[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix server",
  "npm install --prefix frontend"
]

[phases.build]
cmds = ["npm run build --prefix frontend"]

[start]
cmd = "NODE_ENV=production node server/index.js"